
[package]
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2024"
name = "lm_x"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4"
clap = { version = "4.5.53", features = ["derive"] }
flate2 = "1.1"
fs_extra = "1.3"
inquire = "0.9.1"
napi = { version = "3.8.1", features = ["async"] }
napi-derive = "3.5.0"
tar = "0.4"
thiserror = "2"
tokio = { version = "1.39.3", features = ["full"] }
[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = "symbols"
